# -*- coding: utf-8 -*-
# This script was auto-generated by Sim4Life light version 5.2.1.1375

import numpy
import s4l_v1.analysis as analysis
import s4l_v1.document as document
import s4l_v1.model as model
import s4l_v1.units as units
from s4l_v1 import ReleaseVersion
from s4l_v1 import Unit

try:
	# Define the version to use for default values
	ReleaseVersion.set_active(ReleaseVersion.version5_2)
	
	# Creating the analysis pipeline
	# Adding a new SimulationExtractor
	simulation = document.AllSimulations["Ultrasound Transducer"]
	simulation_extractor = simulation.Results()

	# Adding a new AcousticSensorExtractor
	acoustic_sensor_extractor = simulation_extractor["Overall Field"]
	document.AllAlgorithms.Add(acoustic_sensor_extractor)

	# Adding a new FieldCalculator
	inputs = [acoustic_sensor_extractor.Outputs["p(x,y,z,f)"]]
	field_calculator = analysis.field.FieldCalculator(inputs=inputs)
	field_calculator.Expression = u"F"
	field_calculator.ValueLocation = field_calculator.ValueLocation.enum.CellCenter
	field_calculator.UpdateAttributes()
	document.AllAlgorithms.Add(field_calculator)

	# Adding a new FieldGradientEvaluator
	inputs = [field_calculator.Outputs["Result(x,y,z)"]]
	field_gradient_evaluator = analysis.core.FieldGradientEvaluator(inputs=inputs)
	field_gradient_evaluator.UpdateAttributes()
	document.AllAlgorithms.Add(field_gradient_evaluator)

except Exception as exc:
	import traceback
	traceback.print_exc(exc)
	# Reset active version to default
	ReleaseVersion.reset()
	raise(exc)
